### PR TITLE
WS2 release 2.5.0

### PR DESCRIPTION
**Pull request by mlsamuelson**

### CODE REVIEW

**Review by chill5-0 — APPROVED** [review]
Looks good!

**Review by tbutterf — APPROVED** [review]
Looks good to me.

**Review by chill5-0 — COMMENTED** [review]
Does line 75 need a comma after the curly bracket?

**Comment by tbutterf** [comment]
@chill5-0, in php, you can have a comma on the last item, but in json it isn't allowed. So, it is correct.

**Pull request merged**
