### PR TITLE
WS2 2.6.0 release plus fix for spacing in composer.json files.

### PR DESCRIPTION
**Pull request by mlsamuelson**

### CODE REVIEW

**Comment by chill5-0** [comment]
Compared json files to the testing upstream and they match, looks good to me!

**Review by chill5-0 — APPROVED** [review]
Looks good!

**Comment by mlsamuelson** [comment]
Note on one minor change: In the root composer.json I updated the "name" to match our upstream repo. We've been doing that in the testing upstream repo and it appears it's only used as a label.

**Review by bebaps — APPROVED** [review]
Approved

**Pull request merged**
